import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  bgImage: { 
    flex: 1,
    resizeMode: "cover",
  },
  sceneContent: { 
    flex: 1,
    padding: 20,
  },
  // Header styles
  headerContainer: { 
    marginTop: 60,
    marginLeft: 20,
    alignSelf: 'flex-start',
  },
  title: {
    fontSize: 36,
    fontWeight: "bold",
    color: "white",
    textAlign: "left",
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: -2, height: 1 },
    textShadowRadius: 10,
    letterSpacing: 0.5,
  },
  subtitle: { 
    fontSize: 18,
    color: "white",
    marginTop: 8,
    textAlign: "left",
    fontWeight: '300',
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
    letterSpacing: 0.3,
  },
  // Action buttons
  actionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: -100, 
  },
  actionBtn: { 
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
    padding: 20,
    borderRadius: 16,
    width: "95%",
    height: 70,
    justifyContent: "flex-start",
    gap: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  actionText: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  // Profile Screen
  profileHeader: { 
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    marginTop: -50,
  },
  avatar: { 
    width: 100,
    height: 100,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8, 
    borderWidth: 3,
    borderColor: "rgba(255,255,255,0.3)",
  },
  profileStats: { 
    fontSize: 14,
    color: "rgba(255,255,255,0.8)",
    marginTop: 5,
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 5,
  },
  profileActionsContainer: { 
    width: "100%",
    alignItems: "center",
    marginBottom: 50,
  },
  profileActionBtn: { 
    flexDirection: "row",
    alignItems: "center",
    marginTop: 15,
    padding: 18, 
    borderRadius: 16,
    width: "90%",
    justifyContent: "flex-start",
    gap: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  // Settings Screen
  settingsContainer: {
    width: "100%",
    marginTop: 30,
  },
  settingItem: { 
    flexDirection: "row",
    alignItems: "center",
    padding: 18,
    borderRadius: 16,
    marginBottom: 15,
    gap: 15, 
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
    justifyContent: "space-between",
  },
  settingTextContainer: { 
    flex: 1,
  },
  settingText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
  settingSubtext: { 
    color: "rgba(255,255,255,0.7)",
    fontSize: 14,
    marginTop: 2,
  },
  // Mood Selection Screen
  moodScreen: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  moodContent: { 
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  moodTitle: { 
    fontSize: 36,
    fontWeight: "bold",
    color: "white",
    marginBottom: 10,
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
    letterSpacing: 0.5,
  },
  moodSubtitle: { 
    fontSize: 18,
    color: "rgba(255,255,255,0.8)",
    marginBottom: 40,
    textAlign: "center",
    fontWeight: '300',
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
    letterSpacing: 0.3,
  },
  moodButtons: { 
    width: "100%",
    gap: 15,
  },
  moodBtn: { 
    height: 80,
    borderRadius: 15,
    overflow: 'hidden',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 }, 
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  moodBtnBackground: { 
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  moodBtnBackgroundImage: { 
    borderRadius: 15,
  },
  moodBtnContent: { 
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 20,
    gap: 15,
    flex: 1,
  },
  moodEmoji: { 
    fontSize: 30,
  },
  moodText: { 
    fontSize: 22,
    color: "white",
    fontWeight: "600",
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 5,
    letterSpacing: 0.2,
  },
  // Tab Bar
  tabBar: { 
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 12,
    paddingBottom: 20,
    borderTopWidth: 0,
  },
  tabItem: { 
    justifyContent: "center",
    alignItems: "center",
  },
  tabText: {
    fontSize: 12,
    fontWeight: "500",
    marginTop: 4,
  },
});

export default styles;